---
book_repo: docs-book
layout_repo: docs-layout

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

pcf_header: &local_pcf
  use_local_header: true
  latest_stable_version: 1.7
  changelog_href: http://docs.pivotal.io/pivotalcf/pcf-release-notes/
  local_header_img: /images/cloud_rings.png
  local_header_title: Pivotal Cloud Foundry
public_host: hello

sections:
  - repository:
      name: docs-content
    directory: yugabyte-db
    subnav_template: yugabyte-db_subnav.erb

template_variables:                             # optional

book_title: YugaByte DB Enterprise for PKS
book_repo: docs-book
layout_repo: docs-layout
